---

name: mirror-docker

x-common-envs: &common-envs
  MIRROR_DOMAIN: ${MIRROR_DOMAIN}
  HAPROXY_CERTS_PATH: /usr/local/etc/haproxy/certs
  HAPROXY_ADMIN_PORT: 9999
  HAPROXY_CRT_LIST: /usr/local/etc/haproxy/haproxy.crt.list

services:
  haproxy:
    container_name: mirror-docker-haproxy
    restart: on-failure
    image: haproxy:latest
    user: root
    ports:
      - "443:443"
    volumes:
      - ./haproxy_certs:/usr/local/etc/haproxy/certs
      - ./haproxy.crt.list:/usr/local/etc/haproxy/haproxy.crt.list
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy.pem:/usr/local/etc/haproxy/certs/dummy/haproxy.pem:ro
    environment:
      <<: *common-envs
  certbot:
    container_name: mirror-docker-certbot
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./hook:/etc/letsencrypt/renewal-hooks/post/haproxy:ro
    ports:
      - "80:80"
    environment:
      <<: *common-envs
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
