# syntax=docker/docker-compose:1.0.0
---

name: mirror-docker

services:
  haproxy:
    image: haproxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}-haproxy
    restart: on-failure
    user: root
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./haproxy.pem:/etc/letsencrypt/dummy.pem:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./crts:/usr/local/etc/haproxy/crts:ro
    environment:
      MIRROR_DOMAIN: ${MIRROR_DOMAIN}
  certbot:
    container_name: ${COMPOSE_PROJECT_NAME}-certbot
    image: ghcr.io/yurzs/certbot/certbot:haproxy
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./crts:/usr/local/etc/haproxy/crts
    ports:
      - "80:80"

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
