---

name: mirror-docker

services:
  haproxy:
    container_name: mirror-docker-haproxy
    restart: on-failure
    image: haproxy:latest
    user: root
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    environment:
      MIRROR_DOMAIN: ${MIRROR_DOMAIN}
  certbot:
    container_name: mirror-docker-certbot
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./haproxy.hook:/etc/letsencrypt/renewal-hooks/post/haproxy:ro
    ports:
      - "80:80"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
