# syntax=docker/docker-compose:1.0.0
---

name: mirror-docker

x-common-env: &common-env
  MIRROR_DOMAIN: ${MIRROR_DOMAIN:?MIRROR_DOMAIN is required}

services:
  haproxy:
    image: haproxy:latest
    hostname: ${MIRROR_DOMAIN}
    container_name: ${COMPOSE_PROJECT_NAME}-haproxy
    restart: on-failure
    user: root
    volumes:
      - $PWD/letsencrypt:/etc/letsencrypt
      - $PWD/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - $PWD/crts:/usr/local/etc/haproxy/crts/
# Uncomment if not running multiple container services on the same ports.
#   ports:
#     - "443:443"
#     - "80:80"
    environment:
      <<: *common-env
  certbot:
    container_name: ${COMPOSE_PROJECT_NAME}-certbot
    hostname: ${MIRROR_DOMAIN}
    image: ghcr.io/yurzs/certbot:haproxy
    pull_policy: always
    volumes:
      - $PWD/letsencrypt:/etc/letsencrypt
      - /etc/letsencrypt/renewal-hooks/post/
      - $PWD/crts:/usr/local/etc/haproxy/crts/
    environment:
      <<: *common-env
    command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  haproxy-cluster:
    name: haproxy-cluster
    driver: bridge
