# syntax=docker/docker-compose:1.0.0
---

name: mirror-docker

x-common-envs: &common-envs
  MIRROR_DOMAIN: ${MIRROR_DOMAIN}
  HAPROXY_CERTS_PATH: /etc/haproxy/certbot
  HAPROXY_ADMIN_PORT: 9999
  HAPROXY_CRT_LIST: /usr/local/etc/haproxy/haproxy.crt.list

services:
  haproxy:
    build:
      context: .
      dockerfile_inline: |
        FROM haproxy:latest

        USER root

        ADD haproxy.pem /etc/haproxy/certs/haproxy.pem
        RUN echo "/etc/haproxy/certs/haproxy.pem" > /usr/local/etc/haproxy/haproxy.crt.list

        ADD haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

        RUN mkdir -p /etc/haproxy/certbot
        RUN chown -R haproxy:haproxy /etc/haproxy/certbot
        RUN chown -R haproxy:haproxy /usr/local/etc/haproxy/haproxy.crt.list

        USER haproxy

    container_name: ${COMPOSE_PROJECT_NAME}-haproxy
    restart: on-failure
    user: root
    ports:
      - "443:443"
    volumes:
      - certbot_certs:/etc/haproxy/certbot
    environment:
      <<: *common-envs
  certbot:
    container_name: ${COMPOSE_PROJECT_NAME}-certbot
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./hook:/etc/letsencrypt/renewal-hooks/post/haproxy:ro
    ports:
      - "80:80"
    environment:
      <<: *common-envs
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot_certs: {}
